# Project information
site_name: Notes
site_description: A collection of notes I made for the courses I've taken in Ryerson University
site_author: Jasper Cruz
site_url: https://jsprcrz.github.io/Notes

# Repository
repo_name: jsprcrz/Notes
repo_url: https://github.com/jsprcrz/Notes

# Configuration
theme:
  name: material
  language: en
  favicon: assets/favicon.png
  palette:
    primary: black
    accent: black
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link

extra:
  social:
    - icon: fontawesome/brands/github-square
      link: https://github.com/jsprcrz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jasper-cruz
  analytics:
    provider: google
    property: G-SR44P16LQ4
  generator: true

extra_css:
  - css/katex.css
  - css/custom.css
  - https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Jasper Cruz

markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - tables
  - def_list
  - attr_list
  - md_in_html

  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search
  - tags
  - git-revision-date-localized

# Directory
nav:
  - Preface: "index.md"
  - PDF:
      - Winter 2023: "Term/W2023.md"
      - Fall 2022: "Term/F2022.md"
      - Spring 2022: "Term/S2022.md"
      - Winter 2022: "Term/W2022.md"
      - Fall 2021: "Term/F2021.md"
      - Winter 2021: "Term/W2021.md"
