# Project information
site_name: Notes
site_description: Notes for courses taken in Ryerson University
site_author: Jasper Cruz
site_url: https://jsprcrz.github.io/Notes

# Repository
repo_name: jsprcrz/Notes
repo_url: https://github.com/jsprcrz/Notes

# Configuration
theme:
  name: material
  language: en
  favicon: assets/favicon.png
  palette:
    primary: teal
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/earth-americas
    repo: fontawesome/brands/github
  feautures:
    - search.suggest
    - serach.highlight
    - content.tabs.link

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-square
      link: https://github.com/jsprcrz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jasper-cruz
  analytics:
    provider: google
    property: G-SR44P16LQ4

# Directory
nav:
  - Preface: "index.md"
  - Term:
      - Winter 2022: "Term/W2022.md"
      - Fall 2021: "Term/F2021.md"
